<a href="https://colab.research.google.com/github/nalawneh/jupyter-notebook/blob/main/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

In [17]:
x = np.array((2,4,6,7,8)) #np.array is a function take iterable and return np.ndarray object
type(x)
print(f"x type: {type(x)}\n{x}")

x type: <class 'numpy.ndarray'>
[2 4 6 7 8]


Array Rank: Number of dimensions:

In [19]:
x = np.array((
    [1, 8, 5, 9],
    [4, 8, 9, 7],
    [9, 8, 4, 2]
), dtype=np.float64)
print(f"Array x rank: {x.ndim}")

y = np.zeros(
    (2, 3, 4) # passed as an argument represents the shape of the ndarray
)
print(f"Array y rank: {y.ndim}")

Array x rank: 2
Array y rank: 3


Using np.ndarray.shape to get a tuple contains the ndarray dimensions

In [11]:
print(f"Array x: dimensions: {x.shape}")
print(f"Array y: dimensions: {y.shape}")

Array x: dimensions: (3, 4)
Array y: dimensions: (2, 3, 4)


In [22]:
print(f"DType x: {x.dtype}")
print(f"array x size: {x.size}")

DType x: float64
array x size: 12


In [25]:
np.save("my_array", x) # save np.ndarray to the my_array.npy

c = np.load('my_array.npy')
print(c)

[[1. 8. 5. 9.]
 [4. 8. 9. 7.]
 [9. 8. 4. 2.]]


In [37]:
xz = np.zeros((2, 3), dtype=int) # 2 number of rows, 3 number of columns
xo = np.ones((2, 3), dtype=np.float64)
xf = np.full((2, 3), 7, dtype=np.float64)
xeye = np.eye(5)
xdiag = np.diag([1, 2, 3, 4, 5])
print(f"xz:\n{xz}")
print(f"xo:\n{xo}")
print(f"xf:\n{xf}")
print(f"xeye:\n{xeye}")
print(f"xdiag:\n{xdiag}")

xz:
[[0 0 0]
 [0 0 0]]
xo:
[[1. 1. 1.]
 [1. 1. 1.]]
xf:
[[7. 7. 7.]
 [7. 7. 7.]]
xeye:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
xdiag:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
