<a href="https://colab.research.google.com/github/nalawneh/jupyter-notebook/blob/main/Udacity_Session_5_%2C_AWS_AI_with_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python for Data Analysis by Wes McKinney, published by O'Reilly Media
https://github.com/wesm/pydata-book/tree/3rd-edition

https://www.w3schools.com/python/numpy/default.asp

In [ ]:
import numpy as np
np.random.seed(12345)

In [ ]:
my_arr = np.arange(1_000_000)

my_list = list(range(1_000_000))

In [ ]:
print( type( my_arr) )
print( type( my_list) )


<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
%timeit my_arr2 = my_arr * 2

%timeit my_list2 = [x * 2 for x in my_list]

2.09 ms ± 885 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
The slowest run took 5.59 times longer than the fastest. This could mean that an intermediate result is being cached.
93.5 ms ± 59.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
print( np.array( [1.5, -0.1, 3] ))

[ 1.5 -0.1  3. ]


In [ ]:
import numpy as np
data = np.array( [ [1.5, -0.1, 3], [0, -3, 6.5] ] )
print( data )

[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]


In [ ]:
print( data * 10 )
print()
print( data + data )

[[ 15.  -1.  30.]
 [  0. -30.  65.]]

[[ 3.  -0.2  6. ]
 [ 0.  -6.  13. ]]


In [ ]:
print( data.shape ) # N x M

print( data.dtype )

(2, 3)
float64


In [ ]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1.shape

(5,)

In [ ]:
print( arr1 )

[6.  7.5 8.  0.  1. ]


In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
print( arr2.ndim )
print( arr2.shape )

2
(2, 4)


In [ ]:
print( arr1.dtype )
print( arr2.dtype )

float64
int64


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
tmp= np.zeros((3, 6))
tmp[0] = 10
tmp


array([[10., 10., 10., 10., 10., 10.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [ ]:
np.ones(arr1.shape)


array([1., 1., 1., 1., 1.])

In [ ]:
np.empty((2, 3, 2))

array([[[3.48807209e-315, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print( arr1.dtype )
print( arr2.dtype )

float64
int32


In [ ]:
arr1

array([1., 2., 3.])

In [ ]:
arr = np.array([1, 2, 3, 4, 5] ,  dtype=np.int8)
print( arr.dtype )

float_arr = arr.astype(np.float64)

print( float_arr )
print( float_arr.dtype )

int8
[1. 2. 3. 4. 5.]
float64


In [ ]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print( arr )
print( arr.astype(np.int32) )

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]
[ 3 -1 -2  0 12 10]


In [ ]:
numeric_strings = np.array(["1.25", "-9.6", "42"] )
print((numeric_strings.dtype))
numeric_strings.astype(np.float64)

<U4


array([ 1.25, -9.6 , 42.  ])

In [ ]:

int_array = np.arange(10)

calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

int_array.astype( calibers.dtype )

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print( arr )
print()
print( arr * arr )
print()

[[1. 2. 3.]
 [4. 5. 6.]]

[[ 1.  4.  9.]
 [16. 25. 36.]]



In [ ]:
arr.T

array([[1., 4.],
       [2., 5.],
       [3., 6.]])

In [ ]:
print( arr @ arr.T ) # np.dot( arr , arr.T)
# 2x3 , 3x2

[[14. 32.]
 [32. 77.]]


In [ ]:
print( arr - arr )
print()
print( 1 / arr )
print()
print( arr ** 2 )

[[0. 0. 0.]
 [0. 0. 0.]]

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]

[[ 1.  4.  9.]
 [16. 25. 36.]]


# Break

In [ ]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print( arr1 )
print()
print( arr2 )
print()
print( arr2 > arr1 )
print()
print( (arr2 > arr1).astype(int) )


[1. 2. 3.]

[[ 0.  4.  1.]
 [ 7.  2. 12.]]

[[False  True False]
 [ True False  True]]

[[0 1 0]
 [1 0 1]]


In [ ]:
(arr2 > arr1).astype(int)  * arr2

array([[ 0.,  4.,  0.],
       [ 7.,  0., 12.]])

In [ ]:
arr = np.arange(10)
print(arr)
print( arr[5] )
print( arr[5:8] )


[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]


In [ ]:
arr[5:8] = 12
print( arr )

[ 0  1  2  3  4 12 12 12  8  9]


In [ ]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [ ]:
arr_slice[1] = 12345
print( arr_slice)

[   12 12345    12]


In [ ]:
arr


array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [ ]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print( arr2d )
arr2d[2] # arr2d[ 2 , : ]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([7, 8, 9])

In [ ]:
arr2d[ 2 , : ]

array([7, 8, 9])

In [ ]:
print( arr2d[0][2] )
print( arr2d[0, 2] )

3
3


In [ ]:
print( arr2d[:, 2] )

[3 6 9]


In [ ]:
arr
arr[1:6]

In [ ]:
print( arr2d )
arr2d[:2]

In [ ]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [ ]:
lower_dim_slice = arr2d[1, :2]

In [ ]:
lower_dim_slice.shape

In [ ]:
arr2d[:2, 2]

In [ ]:
arr2d[:, :1]

In [ ]:
arr2d[:2, 1:] = 0
arr2d

# Activity


Create a 2x3 array (matrix) with values ranging from 1 to 9.

In [ ]:
import numpy as np

arr_2d =
print(arr_2d)


Checking array attributes --> shape , size , data type

In [ ]:

arr = np.array([1, 2, 3, 4, 5])
print("Shape:",  )
print("Size:",  )
print("Data type:",  )


Array Operations: Element-wise operations

In [ ]:

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition

# Multiplication


Statistical Operations: Calculating mean, median, and standard deviation

In [ ]:

arr = np.array([1, 2, 3, 4, 5])

print("Mean:",  )
print("Median:",  )
print("Standard deviation:",  )


Reshaping a 1D array to a 2D array

In [ ]:

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr =
print(reshaped_arr)


Create a 3x3 identity matrix.

In [ ]:

identity_matrix =
print(identity_matrix)

Broadcasting: Using broadcasting to add a scalar of 5 to a 1-D array of value [1,2,3]

In [ ]:

result =
print(result)


Advanced Indexing: Boolean indexing , Print values bigger than 2

In [ ]:

arr = np.array([1, 2, 3, 4, 5])



Linear Algebra Operations: Matrix multiplication

Multiply those two matrices: `[[1, 2], [3, 4]]` and `[[5, 6], [7, 8]]`

In [ ]:

print(result)


Random Number Generation: Generating random numbers

Generate 5 random numbers between 0,1

Generate 5 random intigers between 1 and 10

In [ ]:

# Random numbers between 0 and 1
random_numbers =
print(random_numbers)

# Random integers between 1 and 10
random_integers =
print(random_integers)


# Satisfaction survay
https://survey.udacity.com/en/SV_9SmE7BNbUo1604u?id=FpvxS4qJTVOu
